//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter: Amount tendered needs to cover the amount due.
        /// </summary>
        internal static string errorAmountInsufficient {
            get {
                return ResourceManager.GetString("errorAmountInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter: Amount due needs to round at least one crown.
        /// </summary>
        internal static string errorAmountTooSmall {
            get {
                return ResourceManager.GetString("errorAmountTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter: The text you entered is not a valid number.
        /// </summary>
        internal static string errorFormat {
            get {
                return ResourceManager.GetString("errorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter: The number you entered has overflown.
        /// </summary>
        internal static string errorOverflow {
            get {
                return ResourceManager.GetString("errorOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the any key to go again, Escape to exit program.
        /// </summary>
        internal static string promptAgain {
            get {
                return ResourceManager.GetString("promptAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount tendered.
        /// </summary>
        internal static string promptAmountPayed {
            get {
                return ResourceManager.GetString("promptAmountPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount due.
        /// </summary>
        internal static string promptAmountToPay {
            get {
                return ResourceManager.GetString("promptAmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount tendered.
        /// </summary>
        internal static string receiptCash {
            get {
                return ResourceManager.GetString("receiptCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change back.
        /// </summary>
        internal static string receiptChange {
            get {
                return ResourceManager.GetString("receiptChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIPT.
        /// </summary>
        internal static string receiptHeader {
            get {
                return ResourceManager.GetString("receiptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount rounded.
        /// </summary>
        internal static string receiptRounding {
            get {
                return ResourceManager.GetString("receiptRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string receiptSubtotal {
            get {
                return ResourceManager.GetString("receiptSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string receiptTotal {
            get {
                return ResourceManager.GetString("receiptTotal", resourceCulture);
            }
        }
    }
}
